### PR TITLE
No needs to use map on unminified js

### PR DESCRIPTION
**Pull request by wbotelhos**
It will rise 404 if I do not copy the map file, but we do not need it since we can read the unminified file.

### CODE REVIEW

**Comment by tocker** [comment]
Hi @wbotelhos,
Thanks for the pull request!
The `js/jquery.cloudinary.js` file is generated during the build process, so editing directly will have no effect on future releases.

This issues was fixed in version 2.1.1

**Comment by wbotelhos** [comment]
I see. I was looking on repository `https://www.npmjs.com/package/cloudinary_js`, but there is other `https://www.npmjs.com/package/cloudinary-jquery`. What is the difference? On the last one has a newer version, but on `package.json` the name is `cloudinary_js`, no `cloudinary-jquery`.

**Comment by tocker** [comment]
cloudinary_js is our original JS library. We split the library to three separate libraries: cloudinary-core, cloudinary-jquery and cloudinary-jquery-file-upload.
We maintain the sources (as well as issues and pull requests) of our JavaScript libraries in cloudinary_js. It is also still published under the name "cloudinary_js" in npm to maintain backward compatibility. 

See https://github.com/cloudinary/cloudinary_js#new-api

**Comment by wbotelhos** [comment]
Thank you, @tocker.

**Pull request closed without merging**
